dist: bionic
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - libcurl4-openssl-dev

install:
  - export CXX="g++-5" CC="gcc-5";

script:
- g++-5 --version
- cd buildtools
- cmake .. -DSLEEPY_DISCORD_BUILD_EXAMPLES=1
- make
